### ISSUE TITLE
t.canvas.__history.toApply() undefined

### ISSUE THREAD

**Issue by Vaeblo** [davidenke/context-filter-polyfill#31]
Since a few days, on iOS devices, the function `drawImage()` leads sometimes to this error : `TypeError : undefined is not an object (evaluating 't.canvas.__history.applyTo')`

Kinda disturbing but with iOS nothing is a surprise anymore.

**Comment by dubocr** [comment]
Hi,

History is undefined at this point when calling `drawImage` without any filter: https://github.com/davidenke/context-filter-polyfill/blob/f844e25a64f6e16752cc8effcb90d3abd2381ff1/src/utils/proxy.utils.ts#L61

**Comment by davidenke** [comment]
Fixed in 0.3.16

**Comment by ARezaK** [comment]
just wanted to chime in that we're still having this issue with 0.3.16

**Comment by davidenke** [comment]
> just wanted to chime in that we're still having this issue with 0.3.16

Could you provide some information how your setup looks like? Or some details fir reproduction?
